site_name: GUI_environments
theme: readthedocs
pages:
- Overview: GUI_environments.md
- Preparation, overview: prep.md
- Preparation, list of participants: prep_list.md
- preparation, varianza files: prep_varriance.md
- Usage: usage.md
- Exploring the outputs: exploring_outputs.md
- Rationale: rationale.md
- Tips: tips.md
- Known issues: known_issues.md
- Installation and set-up: install_and_setup.md