site_name: GUI_environments
theme: readthedocs
pages:
- Overview: GUI_environments.md
- Preparation: prep.md
- Prep., get list of participants using scout_bids_for_gui_env: prep_list.md
- Usage: usage.md
- Exploring the outputs: exploring_outputs.md
- Rationale: rationale.md
- Tips: tips.md
- Known issues: known_issues.md
- Installation and set-up: install_and_setup.md